import { execFileSync } from "node:child_process";
import { readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const SOURCE = path.resolve("scripts/run-v8-entry-exit-grid-fixed-signal-3fos.ts");
const GENERATED = path.resolve("scripts/.generated-v8-kosdaq-untouched-candidates.ts");
const HOLDOUT_YEARS = [2019, 2020, 2021, 2023, 2024] as const;

function replaceExactly(source: string, pattern: RegExp, replacement: string, label: string) {
  const matches = source.match(pattern);
  if (!matches || matches.length !== 1) {
    throw new Error(`${label} replacement expected exactly once, got ${matches?.length ?? 0}`);
  }
  return source.replace(pattern, replacement);
}

async function main() {
  let source = await readFile(SOURCE, "utf8");

  source = replaceExactly(
    source,
    /const STUDY_VERSION = "CloudTrend V8 Entry Exit Grid Fixed-Signal 3-FOS" as const;/g,
    'const STUDY_VERSION = "CloudTrend V8 KOSDAQ Untouched Candidate Validation" as const;',
    "study version",
  );
  source = replaceExactly(
    source,
    /const FOLD_YEARS = \[2018, 2022, 2025\] as const;/g,
    `const FOLD_YEARS = [${HOLDOUT_YEARS.join(", ")}] as const;`,
    "holdout years",
  );
  source = replaceExactly(
    source,
    /const ENTRY_THRESHOLDS = \[6, 6\.5, 7, 7\.5, 8, 8\.5\];/g,
    "const ENTRY_THRESHOLDS = [8];",
    "entry thresholds",
  );
  source = replaceExactly(
    source,
    /const MARKETS = \["KOSDAQ", "KOSPI"\] as const;/g,
    'const MARKETS = ["KOSDAQ"] as const;',
    "markets",
  );
  source = replaceExactly(
    source,
    /const EXIT_SCENARIOS: ExitScenario\[\] = \[\];[\s\S]*?\ninterface CapacitySpec \{/g,
    `const EXIT_SCENARIOS: ExitScenario[] = [
  {
    id: "KOSDAQ-E8-U9-D4-H30",
    label: "BALANCED: KOSDAQ 8.0 entry / 9.0 upside / 4.0 downside / 30D",
    market: "KOSDAQ",
    entryThreshold: 8,
    upsideExitThreshold: 9,
    downsideExitThreshold: 4,
    maxHoldingDays: 30,
  },
  {
    id: "KOSDAQ-E8-U9-D3-H60",
    label: "RETURN: KOSDAQ 8.0 entry / 9.0 upside / 3.0 downside / 60D",
    market: "KOSDAQ",
    entryThreshold: 8,
    upsideExitThreshold: 9,
    downsideExitThreshold: 3,
    maxHoldingDays: 60,
  },
  {
    id: "KOSDAQ-E8-U8.5-D5-H30",
    label: "DEFENSIVE: KOSDAQ 8.0 entry / 8.5 upside / 5.0 downside / 30D",
    market: "KOSDAQ",
    entryThreshold: 8,
    upsideExitThreshold: 8.5,
    downsideExitThreshold: 5,
    maxHoldingDays: 30,
  },
];

interface CapacitySpec {`,
    "fixed candidate scenarios",
  );
  source = replaceExactly(
    source,
    / {2}const baselineReplay = \{ checked: false, passed: false, comparisons: 0 \};[\s\S]*?\n {2}const createdAt = new Date\(\)\.toISOString\(\);/g,
    `  const baselineReplay = {
    checked: false,
    passed: false,
    comparisons: 0,
    note: "Not applicable to untouched folds; the workflow pins src to the verified V8-11b commit.",
  };

  const createdAt = new Date().toISOString();`,
    "3-FOS baseline replay block",
  );
  source = replaceExactly(
    source,
    /Every scenario uses identical fold-year-plus-all-60-bar-candidate runoff evaluation dates; idle cash earns zero\. Fold outcomes are not a continuous 3-year investment\./g,
    "Every scenario uses identical fold-year-plus-all-60-bar-candidate runoff evaluation dates; idle cash earns zero. Fold outcomes are not a continuous multi-year investment.",
    "fold-window note",
  );
  source = replaceExactly(
    source,
    /Exploratory re-analysis of already reviewed 2018\/2022\/2025 folds; ranking is NOT a new untouched OOS test or proof of a universal optimum\./g,
    "Primary untouched validation uses 2019/2020/2021/2023/2024 folds, excluded from the 2018/2022/2025 grid selection. Candidate parameters were frozen before this run; no holdout tuning was performed.",
    "holdout note",
  );

  source = source.replaceAll(
    "v8-entry-exit-grid-fixed-signal-3fos",
    "v8-kosdaq-untouched-candidates",
  );

  const banner = `// GENERATED by run-v8-kosdaq-untouched-candidates.ts\n// Primary holdout years: ${HOLDOUT_YEARS.join(", ")}\n// Candidate parameters are frozen before this run; do not use this script for further tuning.\n`;
  await writeFile(GENERATED, `${banner}${source}`, "utf8");

  try {
    execFileSync("npx", ["vite-node", GENERATED, ...process.argv.slice(2)], {
      cwd: process.cwd(),
      env: process.env,
      stdio: "inherit",
    });
  } finally {
    await rm(GENERATED, { force: true });
  }
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
  process.exitCode = 1;
});
