/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as DataStatusRouteImport } from './routes/data-status'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PositionSizingRouteImport } from './routes/position-sizing'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as InstrumentSymbolRouteImport } from './routes/instrument.$symbol'
import { Route as ScreenerEtfsRouteImport } from './routes/screener.etfs'
import { Route as ScreenerStocksRouteImport } from './routes/screener.stocks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStatusRoute = DataStatusRouteImport.update({
  id: '/data-status',
  path: '/data-status',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionSizingRoute = PositionSizingRouteImport.update({
  id: '/position-sizing',
  path: '/position-sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentSymbolRoute = InstrumentSymbolRouteImport.update({
  id: '/instrument/$symbol',
  path: '/instrument/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerEtfsRoute = ScreenerEtfsRouteImport.update({
  id: '/screener/etfs',
  path: '/screener/etfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerStocksRoute = ScreenerStocksRouteImport.update({
  id: '/screener/stocks',
  path: '/screener/stocks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/data-status': typeof DataStatusRoute
  '/history': typeof HistoryRoute
  '/position-sizing': typeof PositionSizingRoute
  '/scoring': typeof ScoringRoute
  '/sectors': typeof SectorsRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
  '/screener/etfs': typeof ScreenerEtfsRoute
  '/screener/stocks': typeof ScreenerStocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/data-status': typeof DataStatusRoute
  '/history': typeof HistoryRoute
  '/position-sizing': typeof PositionSizingRoute
  '/scoring': typeof ScoringRoute
  '/sectors': typeof SectorsRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
  '/screener/etfs': typeof ScreenerEtfsRoute
  '/screener/stocks': typeof ScreenerStocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/data-status': typeof DataStatusRoute
  '/history': typeof HistoryRoute
  '/position-sizing': typeof PositionSizingRoute
  '/scoring': typeof ScoringRoute
  '/sectors': typeof SectorsRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
  '/screener/etfs': typeof ScreenerEtfsRoute
  '/screener/stocks': typeof ScreenerStocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/data-status'
    | '/history'
    | '/position-sizing'
    | '/scoring'
    | '/sectors'
    | '/instrument/$symbol'
    | '/screener/etfs'
    | '/screener/stocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/data-status'
    | '/history'
    | '/position-sizing'
    | '/scoring'
    | '/sectors'
    | '/instrument/$symbol'
    | '/screener/etfs'
    | '/screener/stocks'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/data-status'
    | '/history'
    | '/position-sizing'
    | '/scoring'
    | '/sectors'
    | '/instrument/$symbol'
    | '/screener/etfs'
    | '/screener/stocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  DataStatusRoute: typeof DataStatusRoute
  HistoryRoute: typeof HistoryRoute
  PositionSizingRoute: typeof PositionSizingRoute
  ScoringRoute: typeof ScoringRoute
  SectorsRoute: typeof SectorsRoute
  InstrumentSymbolRoute: typeof InstrumentSymbolRoute
  ScreenerEtfsRoute: typeof ScreenerEtfsRoute
  ScreenerStocksRoute: typeof ScreenerStocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-status': {
      id: '/data-status'
      path: '/data-status'
      fullPath: '/data-status'
      preLoaderRoute: typeof DataStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-sizing': {
      id: '/position-sizing'
      path: '/position-sizing'
      fullPath: '/position-sizing'
      preLoaderRoute: typeof PositionSizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrument/$symbol': {
      id: '/instrument/$symbol'
      path: '/instrument/$symbol'
      fullPath: '/instrument/$symbol'
      preLoaderRoute: typeof InstrumentSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener/etfs': {
      id: '/screener/etfs'
      path: '/screener/etfs'
      fullPath: '/screener/etfs'
      preLoaderRoute: typeof ScreenerEtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener/stocks': {
      id: '/screener/stocks'
      path: '/screener/stocks'
      fullPath: '/screener/stocks'
      preLoaderRoute: typeof ScreenerStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  DataStatusRoute: DataStatusRoute,
  HistoryRoute: HistoryRoute,
  PositionSizingRoute: PositionSizingRoute,
  ScoringRoute: ScoringRoute,
  SectorsRoute: SectorsRoute,
  InstrumentSymbolRoute: InstrumentSymbolRoute,
  ScreenerEtfsRoute: ScreenerEtfsRoute,
  ScreenerStocksRoute: ScreenerStocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
