/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataStatusRouteImport } from './routes/data-status'
import { Route as PositionSizingRouteImport } from './routes/position-sizing'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as InstrumentSymbolRouteImport } from './routes/instrument.$symbol'
import { Route as ScreenerEtfsRouteImport } from './routes/screener.etfs'
import { Route as ScreenerStocksRouteImport } from './routes/screener.stocks'
import { Route as ApiPublicDebugCandlesRouteImport } from './routes/api/public/debug-candles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStatusRoute = DataStatusRouteImport.update({
  id: '/data-status',
  path: '/data-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionSizingRoute = PositionSizingRouteImport.update({
  id: '/position-sizing',
  path: '/position-sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentSymbolRoute = InstrumentSymbolRouteImport.update({
  id: '/instrument/$symbol',
  path: '/instrument/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerEtfsRoute = ScreenerEtfsRouteImport.update({
  id: '/screener/etfs',
  path: '/screener/etfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerStocksRoute = ScreenerStocksRouteImport.update({
  id: '/screener/stocks',
  path: '/screener/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugCandlesRoute = ApiPublicDebugCandlesRouteImport.update({
  id: '/api/public/debug-candles',
  path: '/api/public/debug-candles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-status': typeof DataStatusRoute
  '/position-sizing': typeof PositionSizingRoute
  '/sectors': typeof SectorsRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
  '/screener/etfs': typeof ScreenerEtfsRoute
  '/screener/stocks': typeof ScreenerStocksRoute
  '/api/public/debug-candles': typeof ApiPublicDebugCandlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-status': typeof DataStatusRoute
  '/position-sizing': typeof PositionSizingRoute
  '/sectors': typeof SectorsRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
  '/screener/etfs': typeof ScreenerEtfsRoute
  '/screener/stocks': typeof ScreenerStocksRoute
  '/api/public/debug-candles': typeof ApiPublicDebugCandlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-status': typeof DataStatusRoute
  '/position-sizing': typeof PositionSizingRoute
  '/sectors': typeof SectorsRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
  '/screener/etfs': typeof ScreenerEtfsRoute
  '/screener/stocks': typeof ScreenerStocksRoute
  '/api/public/debug-candles': typeof ApiPublicDebugCandlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-status'
    | '/position-sizing'
    | '/sectors'
    | '/instrument/$symbol'
    | '/screener/etfs'
    | '/screener/stocks'
    | '/api/public/debug-candles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-status'
    | '/position-sizing'
    | '/sectors'
    | '/instrument/$symbol'
    | '/screener/etfs'
    | '/screener/stocks'
    | '/api/public/debug-candles'
  id:
    | '__root__'
    | '/'
    | '/data-status'
    | '/position-sizing'
    | '/sectors'
    | '/instrument/$symbol'
    | '/screener/etfs'
    | '/screener/stocks'
    | '/api/public/debug-candles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataStatusRoute: typeof DataStatusRoute
  PositionSizingRoute: typeof PositionSizingRoute
  SectorsRoute: typeof SectorsRoute
  InstrumentSymbolRoute: typeof InstrumentSymbolRoute
  ScreenerEtfsRoute: typeof ScreenerEtfsRoute
  ScreenerStocksRoute: typeof ScreenerStocksRoute
  ApiPublicDebugCandlesRoute: typeof ApiPublicDebugCandlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-status': {
      id: '/data-status'
      path: '/data-status'
      fullPath: '/data-status'
      preLoaderRoute: typeof DataStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-sizing': {
      id: '/position-sizing'
      path: '/position-sizing'
      fullPath: '/position-sizing'
      preLoaderRoute: typeof PositionSizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrument/$symbol': {
      id: '/instrument/$symbol'
      path: '/instrument/$symbol'
      fullPath: '/instrument/$symbol'
      preLoaderRoute: typeof InstrumentSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener/etfs': {
      id: '/screener/etfs'
      path: '/screener/etfs'
      fullPath: '/screener/etfs'
      preLoaderRoute: typeof ScreenerEtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener/stocks': {
      id: '/screener/stocks'
      path: '/screener/stocks'
      fullPath: '/screener/stocks'
      preLoaderRoute: typeof ScreenerStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug-candles': {
      id: '/api/public/debug-candles'
      path: '/api/public/debug-candles'
      fullPath: '/api/public/debug-candles'
      preLoaderRoute: typeof ApiPublicDebugCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataStatusRoute: DataStatusRoute,
  PositionSizingRoute: PositionSizingRoute,
  SectorsRoute: SectorsRoute,
  InstrumentSymbolRoute: InstrumentSymbolRoute,
  ScreenerEtfsRoute: ScreenerEtfsRoute,
  ScreenerStocksRoute: ScreenerStocksRoute,
  ApiPublicDebugCandlesRoute: ApiPublicDebugCandlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
