begin;

create table if not exists public.shadow_replay_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  market text not null check (market in ('KR','US')),
  signal_date date not null,
  calculated_at timestamptz not null,
  source_captured_at timestamptz,
  model_available_at timestamptz,
  model_decision_at timestamptz,
  execution_at timestamptz,
  replay_mode text not null check (replay_mode in ('CONTEMPORANEOUS','RETROSPECTIVE')),
  status text not null check (status in ('RECORDED','REUSED','WAITING_INPUT','FAILED')),
  source_hash text check (source_hash is null or source_hash ~ '^sha256:[a-f0-9]{64}$'),
  strategy_version text not null,
  reason text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default pg_catalog.statement_timestamp()
);

alter table public.shadow_replay_audit enable row level security;

revoke all on table public.shadow_replay_audit from public, anon, authenticated, service_role;
grant select, insert on table public.shadow_replay_audit to authenticated;
grant select, insert on table public.shadow_replay_audit to service_role;

drop policy if exists shadow_replay_audit_owner_select on public.shadow_replay_audit;
create policy shadow_replay_audit_owner_select
on public.shadow_replay_audit
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists shadow_replay_audit_owner_insert on public.shadow_replay_audit;
create policy shadow_replay_audit_owner_insert
on public.shadow_replay_audit
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create index if not exists shadow_replay_audit_owner_market_time_idx
on public.shadow_replay_audit(user_id, market, calculated_at desc, id desc);

create index if not exists shadow_replay_audit_owner_signal_idx
on public.shadow_replay_audit(user_id, market, signal_date, calculated_at desc);

create or replace function public.reject_shadow_replay_audit_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'shadow_replay_audit is append-only';
end;
$$;

revoke all on function public.reject_shadow_replay_audit_mutation() from public, anon, authenticated, service_role;

drop trigger if exists shadow_replay_audit_no_update_delete on public.shadow_replay_audit;
create trigger shadow_replay_audit_no_update_delete
before update or delete on public.shadow_replay_audit
for each row execute function public.reject_shadow_replay_audit_mutation();

commit;
